import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './provider'
import { AuthProvider } from '../contexts/AuthContext'
import { MessageProvider } from '../contexts/MessageContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Quyetdaik',
  description: 'Generated by Quyetdaik',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/jsm-logo.png" sizes="any" />
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <AntdRegistry>
            <MessageProvider>
              <AuthProvider>{children}</AuthProvider>
            </MessageProvider>
          </AntdRegistry>
        </ThemeProvider>
      </body>
    </html>
  )
}
